<a href="https://colab.research.google.com/github/LemonMeringue01/DataPreprocessingWorkbookTry/blob/main/(Student)_Data_Preprocessing_%2B_Model_Evaluation_Workbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Codes from ACE6233 Chapter 2 lecture slides

## Source the Data, and Data Preprocessing

Read from a CSV file

defining names here gives the values categories. These can be predetermined in the csv file, using a header line.

In [71]:
from pandas import read_csv
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
df = read_csv('https://raw.githubusercontent.com/wooihaw/datasets/main/pima-indians-diabetes.data.csv', names=names)

`df` is a pandas DataFrame

In [72]:
type(df)

pandas.core.frame.DataFrame

In [73]:
df.shape

(768, 9)

How many columns are there?

ans: 9

Statistical summary of the data

In [74]:
df.describe()

,preg,plas,pres,skin,test,mass,pedi,age,class
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

How many classes are there?

In [75]:
# Hint: df.groupby('class')
print(df['class'].unique())
print(df.groupby('class').count())

[1 0]
       preg  plas  pres  skin  test  mass  pedi  age
class
0       500   500   500   500   500   500   500  500
1       268   268   268   268   268   268   268  268

ans: 2? that being 0 and 1?

Separate the columns into **Features** & **Target**

In [76]:
X = df.drop('test', axis=1)  # Drop target column to get features
y = df['test']

Features in X, Target (Label) in y

In [77]:
type(x)

int

In [78]:
print(X)

     preg  plas  pres  skin  mass   pedi  age  class
0       6   148    72    35  33.6  0.627   50      1
1       1    85    66    29  26.6  0.351   31      0
2       8   183    64     0  23.3  0.672   32      1
3       1    89    66    23  28.1  0.167   21      0
4       0   137    40    35  43.1  2.288   33      1
..    ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48  32.9  0.171   63      0
764     2   122    70    27  36.8  0.340   27      0
765     5   121    72    23  26.2  0.245   30      0
766     1   126    60     0  30.1  0.349   47      1
767     1    93    70    31  30.4  0.315   23      0

[768 rows x 8 columns]

In [79]:
print(y)

0        0
1        0
2        0
3       94
4      168
      ...
763    180
764      0
765    112
766      0
767      0
Name: test, Length: 768, dtype: int64

**How do we handle missing values?**

Example:

In [80]:
import pandas as pd

In [81]:
df1 = pd.DataFrame({'Age': [17, 23, 'x', 38, 54, 67, 32],
                  'Height': [160, 172, 150, 165, 163, 158, 175],
                  'Weight':[50, 68, 43, 52, 47, 49, 'x']})
print(df1)

  Age  Height Weight
0  17     160     50
1  23     172     68
2   x     150     43
3  38     165     52
4  54     163     47
5  67     158     49
6  32     175      x

In [82]:
df1.Age

0    17
1    23
2     x
3    38
4    54
5    67
6    32
Name: Age, dtype: object

In [83]:
type(df1.Age)

pandas.core.series.Series

In [84]:
df1.keys()

Index(['Age', 'Height', 'Weight'], dtype='object')

In [85]:
df1.values

array([[17, 160, 50],
       [23, 172, 68],
       ['x', 150, 43],
       [38, 165, 52],
       [54, 163, 47],
       [67, 158, 49],
       [32, 175, 'x']], dtype=object)

In [86]:
type(df1.values)

numpy.ndarray

Replace the missing values 'x' with NaN

In [104]:
import numpy as np
df1 = df1.replace('x', nan) #just called on the dataframe as a whole. Was massively overcomplicating. This sucks ass.
df1.values

array([[ 17., 160.,  50.],
       [ 23., 172.,  68.],
       [ nan, 150.,  43.],
       [ 38., 165.,  52.],
       [ 54., 163.,  47.],
       [ 67., 158.,  49.],
       [ 32., 175.,  nan]])

In [105]:
df2 = df1.copy() # Keep a copy of df1 for latter use
df3 = df1.copy() # Keep a copy of df1 for latter use

**Method 1: Discard**  
Drop rows with NaN

In [106]:
# Hint: dropna()
df1.dropna()

    Age  Height  Weight
0  17.0     160    50.0
1  23.0     172    68.0
3  38.0     165    52.0
4  54.0     163    47.0
5  67.0     158    49.0

**Method 2: Replace NaN with some value**

Replace NaN with the median value of the column

Replace NaN with the mean value of the column

In [90]:
print(df2)

    Age  Height  Weight
0  17.0     160    50.0
1  23.0     172    68.0
2   NaN     150    43.0
3  38.0     165    52.0
4  54.0     163    47.0
5  67.0     158    49.0
6  32.0     175     NaN

**Feature Scaling**

Load the PIMA dataset

In [91]:
array = df.values

Separate the array into Features & Target

**1. Min-max scaling**

In [92]:
from sklearn.preprocessing import MinMaxScaler

Check the min and max values of Column 1

**2. Standard scaling**

In [93]:
from sklearn.preprocessing import StandardScaler

Check the mean and standard deviation of Column 1

**3. Robust Scaling**

In [94]:
from sklearn.preprocessing import RobustScaler

Check the median and interquartile range (IQR) values

**Handling Categorical Data**

Use `pandas` to encode **ordinal** and **nominal** categorical data

Example:

In [95]:
df0 = pd.DataFrame({'year':[2015, 2017, 2013, 2018, 2020],
                    'make':['Toyota', 'Honda', 'Perodua', 'Hyundai', 'Toyota'],
                    'engine':[1.5, 1.8, 1.3, 1.6, 1.8],
                    'review':['moderate', 'good', 'poor', 'moderate', 'good']})

Encode **ordinal** data

In [96]:
mapping = {'poor':1, 'moderate':2, 'good':3}

In [97]:
df0['review'] = df0['review'].map(mapping)
print(df0)

   year     make  engine  review
0  2015   Toyota     1.5       2
1  2017    Honda     1.8       3
2  2013  Perodua     1.3       1
3  2018  Hyundai     1.6       2
4  2020   Toyota     1.8       3

Encode **nominal** data using `get_dummies`

**Feature Engineering**

Load the PIMA dataset. Create 2 new features for it.

In [98]:
df['plas_pres'] = df['plas'] + df['pres'] # new feature 1

win_size = 3
df['mass_ave'] = df['mass'].rolling(win_size).mean() # new feature 2

Examine the first 5 rows

**Feature Selection**

Try with different methods: Select K Best, Select From Model, Recursive Feature Elimination (RFE), Dimensionality Reduction

In [99]:
from sklearn.feature_selection import SelectKBest, SelectFromModel, RFE

1. **Univariate** Selection

Select 4 best features

In [100]:
# Hint: SelectKBest(k=4)

Show selected features

In [101]:
print([names[i] for i in range(len(names)-1) if selected[i]])

NameError: name 'selected' is not defined

2. **Model-based** Selection

First, choose a model. Here we choose the Random Forest Classifier.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
# Hint: SelectFromModel(RandomForestClassifier(),

Show selected features

In [ ]:
print([names[i] for i in range(len(names)-1) if selected[i]])

3.**Recursive Feature Elimination**

First, choose a model. Here we choose the Decision Tree Classifier.

In [ ]:
from sklearn.tree import DecisionTreeClassifier
# Hint: RFE(DecisionTreeClassifier(),

Show selected features

In [ ]:
print([names[i] for i in range(len(names)-1) if selected[i]])

4. **Dimensionality Reduction**

Use Principal Component Analysis (PCA). Decide on the number of principal components, say 3.

In [ ]:
from sklearn.decomposition import PCA
# Hint: PCA(n_components=3)

Summarize the selected components

In [ ]:
print("Explained Variance: %s" % pca.explained_variance_ratio_)

## Model Evaluation

1. **Hold-out Validation**

Do a Train-Test split. Decide on the Test size, say 20% of the dataset.

In [ ]:
from sklearn.model_selection import train_test_split

Choose a model, say K-Neighbors Classifier.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()

Training

Testing

What's the accuracy?

2. **K-fold Cross-validation**

Do a 5-fold cross-validation

In [ ]:
from sklearn.model_selection import KFold, cross_val_score
# Hint: KFold(n_splits=5,

In [ ]:
results =

**Performance Metrics**

In [ ]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report

1. Confusion Matrix

In [ ]:
predictions = model.predict(X_test)
# Hint: Use confusion_matrix( ), followed by ConfusionMatrixDisplay( )

2. Classification Report

In [ ]:
print(classification_report(y_test, predictions))

**Yellowbrick**'s ClassificationReport

In [ ]:
from yellowbrick.classifier import ClassificationReport
report = ClassificationReport(model, support=True)

What are the results?

**Hyperparameter Tuning**

Choose a model, say Support Vector Classifier (SVC).

In [ ]:
from sklearn.svm import SVC
model = SVC()

**GridSearchCV** - Exhaustive search over specified parameter values for an estimator

In [ ]:
from sklearn.model_selection import GridSearchCV
params = dict(C=[0.001, 0.01, 0.1, 1, 10], gamma=[0.001, 0.01, 0.1, 1, 10])

Here we go

What are the parameter values that give the best score?